#!/usr/bin/env bash

set -euo pipefail

#MISE dir="{{ config_root }}/server"
#MISE description="Tag the gram CLI with an updated version."
#MISE sources=["server/cmd/cli/gram/version/*.go"]

REPO_ROOT=$(git rev-parse --show-toplevel)
VERSION_FILE="$REPO_ROOT/server/cmd/cli/gram/version/version.go"

VERSION=

detect_version() {
  VERSION="$(grep 'const Version = ' "$VERSION_FILE" |
    sed 's/const Version = "\(.*\)"/\1/')"
}

looks_like_semver() {
    [[ "$1" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]
}

verify_version() {
  if ! looks_like_semver "$VERSION"; then
    echo "Error: Version '$VERSION' does not look like semantic version (vX.Y.Z)"
    exit 1
  fi

  ask_version_correct
}

ask_version_correct() {
  echo "Current version: $VERSION ($VERSION_FILE)"
  echo
  read -p "Is this the correct version to tag? Have you bumped it if needed? (y/N): " -r
  echo

  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Please update the version in $VERSION_FILE and re-run this task."
    exit 1
  fi
}

tag_version() {
  local tag="server/cmd/cli/gram/$VERSION"
  set -x
  git tag "$tag"
  set +x

  echo "Successfully tagged commit with $tag"
  echo "You can now push the tag with: git push origin $tag"
}

main() {
  detect_version
  verify_version
  tag_version
}

main "$@"