name: CLI Test

on:
  pull_request:
    branches:
      - main
      - cli

jobs:
  hello:
    name: Iterate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run CLI
        run: go run server/cli/main.go
